boot.o: boot.S multiboot.h x86_desc.h types.h
handler_interface.o: handler_interface.S x86_desc.h types.h
paging_setup.o: paging_setup.S paging_setup.h
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handler.o: exception_handler.c exception_handler.h lib.h \
  types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt_init.o: idt_init.c idt_init.h x86_desc.h types.h exception_handler.h \
  lib.h handler_interface.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt_init.h rtc_handler.h keyboard_handler.h paging.h
keyboard_handler.o: keyboard_handler.c lib.h types.h keyboard_handler.h \
  i8259.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h paging_setup.h lib.h
rtc_handler.o: rtc_handler.c lib.h types.h rtc_handler.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
